### ISSUE TITLE
Design Issues

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/bonheur-royale#3]
## Google Fonts Latin Plus coverage

- [x] Design all the glyphs required in the [GF Latin Plus encoding](https://github.com/googlefonts/gftools/blob/main/Lib/gftools/encodings/GF%20Glyph%20Sets/filter%20lists/nice%20names/plus_unique-glyphs.txt)
- [x] Create all the comb marks as mentioned below
- [x] Leave only the compound glyphs (e.g. `adblgrave`) marked in dark grey as pending to be created using the components

----

## Diacritics

- [x] Please ensure the definitive design is adjusted in the combining marks, so they will be ready to create the compound glyphs.
- [x] Once the definitive design is ensured in the `comb` marks Legacy marks, delete the legacy marks and add them back so they are made using the `comb` marks as components.
- [x] Diacritics need to be balanced (in weight, size, contrast) and matching the style of the typeface design.
- [x] Adjust the vertical position using glyphs app locked guidelines.
- [x] Ensure related marks are consistent between them, e.g. `caron` and `circumflex`
- [x] Caron.alt need to have the alternate shape used in `Ľ` [Slovak](https://en.wikipedia.org/wiki/%C4%BD) On page 30 of [this document](http://theinsectsproject.eu/wp-content/uploads/2017/05/Insects-Project-2nd-edition_screen.pdf) you can find detailed info around the vertical Caron.
- [x] Leave a 0 sidebearings value for the marks

![Screen Shot 2021-06-29 at 12 31 33](https://user-images.githubusercontent.com/48698976/123875121-c0086300-d8fe-11eb-9bcb-1eebf87e9fdb.png)
![Screen Shot 2021-06-29 at 12 32 27](https://user-images.githubusercontent.com/48698976/123875128-c1d22680-d8fe-11eb-9a30-61630a4e3b35.png)

----
## Glyphs

- [x] The `ampersand` and `Eng` need to be consistent (in size and style) with the font. See [RUSerius](https://github.com/googlefonts/are-you-serious/issues/2#issuecomment-870693956) as reference
- [x] The German Double SS need to be fixed. This [article](https://www.lucasfonts.com/learn/1E9E) is a good reference

<img width="561" alt="Screen Shot 2021-06-29 at 17 24 28" src="https://user-images.githubusercontent.com/48698976/123875259-f80fa600-d8fe-11eb-8988-48aecabc926b.png">

**Comment by RobLeuschke** [comment]
All tasks have been completed, including the german Dbls:
https://www.dropbox.com/s/tav295tw192fha0/Screen%20Shot%202021-07-03%20at%2012.58.03%20AM.png?dl=0
